from __future__ import annotations

from typing import Protocol

from app.domain import (
    AdminOverview,
    AuthUser,
    LoyaltyCustomer,
    ProductDetail,
    ProductSummary,
    ProductVariant,
    SalesByVariantReport,
    Supplier,
)
from app.schemas import CheckoutRequest, ProductUpsertRequest, VariantUpsertRequest


class EcommerceRepository(Protocol):
    def is_enabled(self) -> bool: ...
    def list_products(self) -> list[ProductSummary]: ...
    def list_product_details(self) -> list[ProductDetail]: ...
    def get_product(self, product_slug: str) -> ProductDetail: ...
    def authenticate_client(self, identifier: str, password: str) -> AuthUser: ...
    def authenticate_admin(self, identifier: str, password: str) -> AuthUser: ...
    def get_customer(self, customer_id: str) -> LoyaltyCustomer: ...
    def create_product(self, payload: ProductUpsertRequest) -> ProductDetail: ...
    def update_product(self, product_slug: str, payload: ProductUpsertRequest) -> ProductDetail: ...
    def create_variant(self, product_slug: str, payload: VariantUpsertRequest) -> ProductVariant: ...
    def update_variant(
        self, product_slug: str, variant_id: str, payload: VariantUpsertRequest
    ) -> ProductVariant: ...
    def checkout(self, payload: CheckoutRequest, sales_channel: str): ...
    def get_sales_report(self) -> list[SalesByVariantReport]: ...
    def get_admin_overview(self) -> AdminOverview: ...
    def list_suppliers(self) -> list[Supplier]: ...
