from __future__ import annotations

from datetime import datetime
from typing import Protocol

from app.domain import (
    AdminOverview,
    AuthUser,
    LoyaltyCustomer,
    OrderSummary,
    Promotion,
    ProductDetail,
    ProductSummary,
    ProductVariant,
    SalesByVariantReport,
    SalesKpisReport,
    Supplier,
)
from app.schemas import (
    CheckoutRequest,
    ProductUpsertRequest,
    PromotionUpsertRequest,
    SupplierUpsertRequest,
    VariantUpsertRequest,
)


class EcommerceRepository(Protocol):
    def is_enabled(self) -> bool: ...
    def list_products(self) -> list[ProductSummary]: ...
    def list_product_details(self) -> list[ProductDetail]: ...
    def get_product(self, product_slug: str) -> ProductDetail: ...
    def authenticate_client(self, identifier: str, password: str) -> AuthUser: ...
    def authenticate_admin(self, identifier: str, password: str) -> AuthUser: ...
    def get_customer(self, customer_id: str) -> LoyaltyCustomer: ...
    def create_customer(self, *, full_name: str, email: str) -> LoyaltyCustomer: ...
    def update_customer(self, customer_id: str, *, full_name: str, email: str | None, phone: str | None) -> LoyaltyCustomer: ...
    def list_customer_orders(self, customer_id: str) -> list[OrderSummary]: ...
    def get_order(self, order_id: str) -> OrderSummary | None: ...
    def create_product(self, payload: ProductUpsertRequest) -> ProductDetail: ...
    def update_product(self, product_slug: str, payload: ProductUpsertRequest) -> ProductDetail: ...
    def delete_product(self, product_slug: str) -> None: ...
    def update_product_image(self, product_slug: str, image_url: str) -> ProductDetail: ...
    def upload_product_image(self, product_slug: str, filename: str, file_bytes: bytes, content_type: str) -> str: ...
    def create_variant(self, product_slug: str, payload: VariantUpsertRequest) -> ProductVariant: ...
    def update_variant(
        self, product_slug: str, variant_id: str, payload: VariantUpsertRequest
    ) -> ProductVariant: ...
    def checkout(self, payload: CheckoutRequest, sales_channel: str): ...
    def get_sales_report(self) -> list[SalesByVariantReport]: ...
    def get_sales_report_filtered(
        self,
        *,
        start_date: datetime | None = None,
        end_date: datetime | None = None,
        sales_channel: str | None = None,
    ) -> list[SalesByVariantReport]: ...
    def get_sales_kpis(
        self,
        *,
        start_date: datetime | None = None,
        end_date: datetime | None = None,
        sales_channel: str | None = None,
    ) -> SalesKpisReport: ...
    def get_admin_overview(self) -> AdminOverview: ...
    def list_suppliers(self) -> list[Supplier]: ...
    def create_supplier(self, payload: SupplierUpsertRequest) -> Supplier: ...
    def update_supplier(self, supplier_id: str, payload: SupplierUpsertRequest) -> Supplier: ...
    def delete_supplier(self, supplier_id: str) -> None: ...
    def list_promotions(self, active_only: bool = True) -> list[Promotion]: ...
    def create_promotion(self, payload: PromotionUpsertRequest) -> Promotion: ...
    def update_promotion(self, promotion_id: str, payload: PromotionUpsertRequest) -> Promotion: ...
    def set_promotion_active(self, promotion_id: str, is_active: bool) -> Promotion: ...
    def delete_promotion(self, promotion_id: str) -> None: ...
